version: '3.7'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg-data:/var/lib/postgresql/data
  app:
    container_name: app
    restart: unless-stopped
    build: ./
    ports:
      - "8000:8000"
    env_file:
      - ./.env

volumes:
  pg-data:
    driver: local